repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
        exclude: \.json$
        include: \.py$
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["--line-length=100"]
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      - id: ruff
        args:
          [
            "--fix",
            "--select=I,UP015,UP032,UP034,UP018,COM,C4,PT,SIM,PLR0402",
            # remove SIM115 after a separate PR to fix the issue
            "--ignore=PT011,PT012,SIM117,PT006",
          ]
      # - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3
        args: ["--max-line-length=100"]
