name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PYTHONVERSION: "3.12"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python and Install dependencies
        if: env.SKIP_RELEASE != 'true'
        run: |
          uv python install ${{ env.PYTHONVERSION }}
          uv venv
          uv pip install .
          uv pip install twine build

      - name: Get version from main
        id: get-main-version
        run: |
          git switch main
          MAIN_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
          git switch -

      - name: Compare versions
        id: compare-versions
        run: |
          CUR_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")

          echo "Current version in pyproject.toml: $CUR_VERSION"
          echo "Version on main branch: $MAIN_VERSION"

          if [ "$CUR_VERSION" == "$MAIN_VERSION" ]; then
            echo "The version hasn't changed. Skipping release."
            echo "SKIP_RELEASE=true" >> $GITHUB_ENV
          else
            echo "Versions differ. Proceed with the release."
            echo "SKIP_RELEASE=false" >> $GITHUB_ENV

      - name: Release to PyPI
        if: env.SKIP_RELEASE != 'true'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_PUBLISHER_TOKEN }}
        run: |
          uv run python -m build --sdist
          uv run twine upload -r testpypi dist/*
